version: 2.1
jobs:
  oldcam:
   docker:
      - image: ghcr.io/neutron-projects/docker-image:arch-neutron
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://ImSpiDy:$ght@github.com/ImSpiDy/kernel_xiaomi_lavender -b snx .
           bash build.sh --old

  qti-quo:
   docker:
      - image: ghcr.io/neutron-projects/docker-image:arch-neutron
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://ImSpiDy:$ght@github.com/ImSpiDy/kernel_xiaomi_lavender -b snx .
           bash build.sh --quo

  qti-old:
   docker:
      - image: ghcr.io/neutron-projects/docker-image:arch-neutron
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://ImSpiDy:$ght@github.com/ImSpiDy/kernel_xiaomi_lavender -b snx .
           bash build.sh --cam

workflows:
  version: 2.1
  cooking:
    jobs:
      - oldcam
      - qti-quo
      - qti-old
