version: 2.1
jobs:
  Ext4:
   docker:
      - image: ghcr.io/neutron-projects/docker-image:arch-neutron
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://github.com/ImSpiDy/kernel_xiaomi_lavender-4.19 -b 13-Test .
           bash build.sh

  EroFs:
   docker:
      - image: ghcr.io/neutron-projects/docker-image:arch-neutron
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://github.com/ImSpiDy/kernel_xiaomi_lavender-4.19 -b 13-Test .
           bash build.sh --EroFs

  RF-Ext4:
   docker:
      - image: ghcr.io/neutron-projects/docker-image:arch-neutron
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://github.com/ImSpiDy/kernel_xiaomi_lavender-4.19 -b R1-Rebase .
           bash build.sh --DynExt4

  RF-EroFs:
   docker:
      - image: ghcr.io/neutron-projects/docker-image:arch-neutron
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://github.com/ImSpiDy/kernel_xiaomi_lavender-4.19 -b 13-Test .
           bash build.sh --DynEroFs

workflows:
  version: 2.1
  cooking:
    jobs:
      - RF-Ext4
